language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

install:
  - Rscript -e "install.packages('tidyverse')"
  - Rscript -e "install.packages('ggforce')"
  - Rscript -e "install.packages('ggrepel')"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('kassambara/factoextra')"

script:
  - ./_build.sh
  - ./_deploy.sh
