--- 
title: "Omics Central"
author: "Amrit Singh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book covers some commonly used to explore and analyze omics data."
---

# Rationale

This project was developed in order to create a resource warehouse for researchers analyze omics datasets of various types such as transcriptomics, proteomcs, metabolomics. I expect this resource to grow as others contribute to it. Think of it as an awesome-resource github repo but in a bookdown format. However, since this book is meant as documentation to the omics central web application, adding new methods will require pull requests to the omics central web app repos (omics-central-frontend, omics-central-backend and omics-central-docker) and bookdown repos (omics-central-learn and omics-central-contribute).

The purpose of this book is not to copy, paste other works but to link works by different authors in one place and explain concepts through the lens of an omics researcher.
